### ISSUE TITLE
Rare segmentation faults when running with many (128) workers

### ISSUE THREAD

**Issue by mhantke** [mhantke/h5writer#1]
Most likely subtle bug in MPI calls...

Core was generated by `python /home/hantke/src/hummingbird/scripts/offline_davinci/../../hummingbird.p'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000000000 in ?? ()

Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6_7.7.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-42.el6.x86_64 libcom_err-1.41.12-22.el6.x86_64 libgcc-4.4.7-16.el6.x86_64 libgfortran-4.4.7-16.el6.x86_64 libgomp-4.4.7-16.el6.x86_64 libibverbs-1.1.8-4.el6.x86_64 libjpeg-turbo-1.2.1-3.el6_5.x86_64 libnl-1.1.4-2.el6.x86_64 libpng-1.2.49-2.el6_7.x86_64 libselinux-2.0.94-5.8.el6.x86_64 libstdc++-4.4.7-16.el6.x86_64 libtiff-3.9.4-10.el6_5.x86_64 libuuid-2.17.2-12.18.el6.x86_64 ncurses-libs-5.7-4.20090207.el6.x86_64 nss-softokn-freebl-3.14.3-23.el6_7.x86_64 openssl-1.0.1e-42.el6_7.2.x86_64 sssd-client-1.12.4-47.el6_7.7.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007f9b2e19da58 in btl_openib_handle_incoming () from /reg/g/psdm/sw/external/openmpi/1.8.6/x86_64-rhel6-gcc44-opt/lib/openmpi/mca_btl_openib.so
#2  0x00007f9b2e19ee2f in poll_device () from /reg/g/psdm/sw/external/openmpi/1.8.6/x86_64-rhel6-gcc44-opt/lib/openmpi/mca_btl_openib.so
#3  0x00007f9b2e19f19c in btl_openib_component_progress () from /reg/g/psdm/sw/external/openmpi/1.8.6/x86_64-rhel6-gcc44-opt/lib/openmpi/mca_btl_openib.so
#4  0x00007f9b36346daa in opal_progress () from /reg/g/psdm/sw/external/openmpi/1.8.6/x86_64-rhel6-gcc44-opt/lib/libopen-pal.so.6
#5  0x00007f9b368ab96d in ompi_request_default_wait_all () from /reg/g/psdm/sw/releases/ana-current/arch/x86_64-rhel6-gcc44-opt/lib/libmpi.so.1
#6  0x00007f9b368dd727 in PMPI_Waitall () from /reg/g/psdm/sw/releases/ana-current/arch/x86_64-rhel6-gcc44-opt/lib/libmpi.so.1
#7  0x00007f9b07fb2f19 in ADIOI_W_Exchange_data () from /reg/g/psdm/sw/external/openmpi/1.8.6/x86_64-rhel6-gcc44-opt/lib/openmpi/mca_io_romio.so
#8  0x00007f9b07fb4c13 in ADIOI_GEN_WriteStridedColl () from /reg/g/psdm/sw/external/openmpi/1.8.6/x86_64-rhel6-gcc44-opt/lib/openmpi/mca_io_romio.so
#9  0x00007f9b07f98298 in MPIOI_File_write_all () from /reg/g/psdm/sw/external/openmpi/1.8.6/x86_64-rhel6-gcc44-opt/lib/openmpi/mca_io_romio.so
#10 0x00007f9b07f987b7 in mca_io_romio_dist_MPI_File_write_at_all () from /reg/g/psdm/sw/external/openmpi/1.8.6/x86_64-rhel6-gcc44-opt/lib/openmpi/mca_io_romio.so
#11 0x00007f9b368e5fa7 in PMPI_File_write_at_all () from /reg/g/psdm/sw/releases/ana-current/arch/x86_64-rhel6-gcc44-opt/lib/libmpi.so.1
#12 0x00007f9b0baaadff in H5FD_mpio_write () from /reg/g/psdm/sw/external/hdf5/1.8.15a/x86_64-rhel6-gcc44-opt/lib/libhdf5.so.10
#13 0x00007f9b0baa64fd in H5FD_write () from /reg/g/psdm/sw/external/hdf5/1.8.15a/x86_64-rhel6-gcc44-opt/lib/libhdf5.so.10
#14 0x00007f9b0ba9320a in H5F__accum_write () from /reg/g/psdm/sw/external/hdf5/1.8.15a/x86_64-rhel6-gcc44-opt/lib/libhdf5.so.10
#15 0x00007f9b0ba96823 in H5F_block_write () from /reg/g/psdm/sw/external/hdf5/1.8.15a/x86_64-rhel6-gcc44-opt/lib/libhdf5.so.10
#16 0x00007f9b0ba60945 in H5D__chunk_allocate () from /reg/g/psdm/sw/external/hdf5/1.8.15a/x86_64-rhel6-gcc44-opt/lib/libhdf5.so.10
#17 0x00007f9b0ba6e951 in H5D__init_storage () from /reg/g/psdm/sw/external/hdf5/1.8.15a/x86_64-rhel6-gcc44-opt/lib/libhdf5.so.10
#18 0x00007f9b0ba6ed31 in H5D__alloc_storage () from /reg/g/psdm/sw/external/hdf5/1.8.15a/x86_64-rhel6-gcc44-opt/lib/libhdf5.so.10
#19 0x00007f9b0ba6f165 in H5D__set_extent () from /reg/g/psdm/sw/external/hdf5/1.8.15a/x86_64-rhel6-gcc44-opt/lib/libhdf5.so.10
#20 0x00007f9b0ba55a14 in H5Dset_extent () from /reg/g/psdm/sw/external/hdf5/1.8.15a/x86_64-rhel6-gcc44-opt/lib/libhdf5.so.10
#21 0x00007f9b0af77ba6 in __pyx_f_4h5py_4defs_H5Dset_extent (__pyx_v_dset_id=<value optimized out>, __pyx_v_size=<value optimized out>) at /home/hantke/src_ext/h5py-2.5.0/h5py/defs.c:6224
#22 0x00007f9b09c83875 in __pyx_pf_4h5py_3h5d_9DatasetID_6set_extent (__pyx_v_self=0x7f9af2553eb0, __pyx_v_shape=0x7f9af247daa0) at /home/hantke/src_ext/h5py-2.5.0/h5py/h5d.c:4282
#23 __pyx_pw_4h5py_3h5d_9DatasetID_7set_extent (__pyx_v_self=0x7f9af2553eb0, __pyx_v_shape=0x7f9af247daa0) at /home/hantke/src_ext/h5py-2.5.0/h5py/h5d.c:4108
#24 0x00007f9b4782c293 in PyObject_Call (func=0x7f9af247cb48, arg=<value optimized out>, kw=<value optimized out>) at Objects/abstract.c:2529
#25 0x00007f9b478d52f3 in PyEval_CallObjectWithKeywords (func=0x7f9af247cb48, arg=0x7f9b2808eb50, kw=<value optimized out>) at Python/ceval.c:3904
#26 0x00007f9b47849fac in methoddescr_call (descr=<value optimized out>, args=0x7f9b2808eb50, kwds=0x0) at Objects/descrobject.c:247
#27 0x00007f9b0b18edcf in __Pyx_PyObject_Call (func=0x7f9b2819ed88, arg=<value optimized out>, kw=<value optimized out>) at /home/hantke/src_ext/h5py-2.5.0/h5py/_objects.c:7982
#28 0x00007f9b0b194942 in __pyx_pf_4h5py_8_objects_9with_phil_wrapper (__pyx_self=<value optimized out>, __pyx_args=0x7f9b3bfb83b0, __pyx_kwds=<value optimized out>)

```
at /home/hantke/src_ext/h5py-2.5.0/h5py/_objects.c:2839
```
#29 __pyx_pw_4h5py_8_objects_9with_phil_1wrapper (__pyx_self=<value optimized out>, __pyx_args=0x7f9b3bfb83b0, __pyx_kwds=<value optimized out>)

```
at /home/hantke/src_ext/h5py-2.5.0/h5py/_objects.c:2759
```
#30 0x00007f9b4782c293 in PyObject_Call (func=0x7f9b28131290, arg=<value optimized out>, kw=<value optimized out>) at Objects/abstract.c:2529
#31 0x00007f9b478dae3a in do_call (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4253
#32 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4058
#33 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2681
#34 0x00007f9b478dd74e in PyEval_EvalCodeEx (co=0x7f9b2810d230, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>, argcount=2, kws=0x7f9af25653f8,

```
kwcount=0, defs=0x7f9b28122328, defcount=1, closure=0x0) at Python/ceval.c:3267
```
#35 0x00007f9b478dbd87 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4131
#36 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4056
#37 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2681
#38 0x00007f9b478dc0db in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4121
#39 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4056
#40 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2681
#41 0x00007f9b478dd74e in PyEval_EvalCodeEx (co=0x7f9b181d9230, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>, argcount=3, kws=0x7f9af255b800,

```
kwcount=0, defs=0x7f9b2812f6a8, defcount=1, closure=0x0) at Python/ceval.c:3267
```
#42 0x00007f9b478dbd87 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4131
#43 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4056
#44 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2681
#45 0x00007f9b478dd74e in PyEval_EvalCodeEx (co=0x7f9b181d9230, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>, argcount=2, kws=0x60652e8,

```
kwcount=0, defs=0x7f9b2812f6a8, defcount=1, closure=0x0) at Python/ceval.c:3267
```
#46 0x00007f9b478dbd87 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4131
#47 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4056
#48 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2681
#49 0x00007f9b478dc0db in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4121
#50 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4056
#51 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2681
#52 0x00007f9b478dd74e in PyEval_EvalCodeEx (co=0x7f9b181d9830, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>, argcount=2, kws=0x4274ba8,

```
kwcount=0, defs=0x7f9b181de668, defcount=1, closure=0x0) at Python/ceval.c:3267
```

---Type <return> to continue, or q <return> to quit---
#53 0x00007f9b478dbd87 in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4131
#54 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4056
#55 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2681
#56 0x00007f9b478dc0db in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4121
#57 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4056
#58 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2681
#59 0x00007f9b478dc0db in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4121
#60 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4056
#61 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2681
#62 0x00007f9b478dc0db in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4121
#63 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4056
#64 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2681
#65 0x00007f9b478dc0db in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4121
#66 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4056
#67 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2681
#68 0x00007f9b478dd74e in PyEval_EvalCodeEx (co=0x7f9b47d48d30, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>, argcount=0, kws=0x0, kwcount=0,

```
defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3267
```
#69 0x00007f9b478dd862 in PyEval_EvalCode (co=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>) at Python/ceval.c:669
#70 0x00007f9b478fd6d0 in run_mod (fp=0xd6cda0, filename=<value optimized out>, start=<value optimized out>, globals=0x7f9b47d65168, locals=0x7f9b47d65168, closeit=1, flags=0x7fff55224890)

```
at Python/pythonrun.c:1371
```
#71 PyRun_FileExFlags (fp=0xd6cda0, filename=<value optimized out>, start=<value optimized out>, globals=0x7f9b47d65168, locals=0x7f9b47d65168, closeit=1, flags=0x7fff55224890)

```
at Python/pythonrun.c:1357
```
#72 0x00007f9b478fd8af in PyRun_SimpleFileExFlags (fp=0xd6cda0, filename=0x7fff552261a8 "/home/hantke/src/hummingbird/scripts/offline_davinci/../../hummingbird.py", closeit=1,

```
flags=0x7fff55224890) at Python/pythonrun.c:949
```
#73 0x00007f9b479131c4 in Py_Main (argc=<value optimized out>, argv=<value optimized out>) at Modules/main.c:640
#74 0x00007f9b46bc6d5d in __libc_start_main () from /lib64/libc.so.6
#75 0x0000000000400659 in _start ()

**Comment by mhantke** [comment]
Does not occur any longer after version 0.2.0.
